==== STATE of this repo: Generally working, but being updated frequently. Still pretty brittle due to lots of hardcoded parameters.


==== Need to fix:
* Need to be able to disable NFS server and NFS StorageClass from within variables.tf file
* Remove hardcoded references to RMT server (done but need to verify)
* Need to be able to pass helm server info into admin node from within variables.tf file
** Could also use cluster-deploy.sh to set keys/values in a file, b64 encode that file then sed it into the admin node cloud-init file
* Found that cluster-deploy.sh is dependent on appropriate entries for the KVM user and hosts in .ssh/config file

==== Dependencies:
* Must use RMT server as Helm server 

==== Deployment overview:
. Install Terraform
. Install the terraform-libvirt-provider
. Download the skuba repo
. Downlod this repo
. Copy the contents of this  repo into the skuba/ci/infra/libvirt directory
. Update terraform.tfvars file with the specifics for your environment
. Update the cluster-deploy.sh script variables with the specifics for your environment
. Ensure the local user has passwordless ssh to the libvirt user specified in .tfvars
. Ensure the libvirt user is in the libvirt group and has passwordless sudo privileges
. Create an entry for the libvirt user on the KVM host in the .ssh/config file
. Start ssh-agent with the ssh key that provides passwordless ssh access
. Deploy with ./cluster-deploy.sh
.. Destroy with ./cluster-destroy.sh


// vim: set syntax=asciidoc:

